### ISSUE TITLE
合约被攻击？

### ISSUE THREAD

**Issue by jin10086** [loveblockchain/eosdice#1]
https://igaojin.me/2018/11/04/EODIDEC-%E9%9A%8F%E6%9C%BA%E6%95%B0%E8%A2%AB%E6%94%BB%E7%A0%B4/

写了一篇文章介绍...

正确的姿势是延迟交易一次，然后再延迟一次 这个可以试一下？

**Comment by jin10086** [comment]
但是奇怪的是 

tapos_block_prefix 

这个数不是未来区块的么？

黑客怎么提前拿到的？

**Comment by loveblockchain** [comment]
謝謝.

原因估計是這樣，
只要黑客拿到當前的區塊hash后，
快速的發送給合約，那麼合約就能算出來 當前區塊的tapos_block_prefix
然後快速的與bocai合約交互（在下一個塊提交成功，則隨機數被破解了）

**Comment by wangyilin1987** [comment]
@jin10086 你好，我不明白为什么需要延迟两次。这样做的用意是什么呢？延迟开奖不就已经能让tapos_block_prefix无法被预测到吗？@loveblockchain 的解释用获取当前区块的tapos_block_prefix，然后迅速与bocai合約交互，我无法理解这样做能计算出未来的tapos_block_prefix值！
下注和开奖不是同时进行的话，用tapos_block_prefix来做为随机源还是不安全的吗？

**Comment by jin10086** [comment]
@wangyilin1987  
可以看下这篇文章，里面几个引用也一起看看，[此地无人生还：区块链随机数的原罪与救赎](https://igaojin.me/2018/11/23/%E6%AD%A4%E5%9C%B0%E6%97%A0%E4%BA%BA%E7%94%9F%E8%BF%98%EF%BC%9A%E5%8C%BA%E5%9D%97%E9%93%BE%E9%9A%8F%E6%9C%BA%E6%95%B0%E7%9A%84%E5%8E%9F%E7%BD%AA%E4%B8%8E%E6%95%91%E8%B5%8E/)

**Comment by wangyilin1987** [comment]
@jin10086 感谢！从引用文章中找到延迟两次的原因了。

**Comment by JayJay1024** [comment]
> @wangyilin1987
> 可以看下这篇文章，里面几个引用也一起看看，[此地无人生还：区块链随机数的原罪与救赎](https://igaojin.me/2018/11/23/%E6%AD%A4%E5%9C%B0%E6%97%A0%E4%BA%BA%E7%94%9F%E8%BF%98%EF%BC%9A%E5%8C%BA%E5%9D%97%E9%93%BE%E9%9A%8F%E6%9C%BA%E6%95%B0%E7%9A%84%E5%8E%9F%E7%BD%AA%E4%B8%8E%E6%95%91%E8%B5%8E/)

如果使用`两次defer`开奖，随机种子除了`tapos_block_num`、`tapos_block_prefix`没有其他可控因子，黑客怎么攻击会呢？我看最近有个游戏就被攻击了，但没披露细节。
